  /background:
    get:
      description: |
        Background resource processes.
      responses:
        200:
          body:
            application/json:
              example: '{"gbifSync":true,"importer":false}'
    put:
      description: |
        Update background resource processes.
      body:
        application/json:
          type: string
          example: '{"gbifSync":false,"importer":true}'
      responses:
        204:
        404:
  /logo-update:
    post:
      description: |
        Update the GSD logos.
      responses:
        200:
          body:
            text/plain:
              type: string
  /sector-count-update:
    post:
      description: |
        Update the sector counts.
      responses:
        200:
          body:
            text/plain:
              type: string
  /reindex:
    post:
      description: |
        Reindex elastic search.
      responses:
        200:
          body:
            text/plain:
              type: string