  /{catKey}:
    get:
      description: |
        Get the assembly status for catalogue {catKey}
      responses:
        200:
          body:
            application/json-assembly-idle:
              example: |
                {
                  "failed": 0,
                  "completed": 0,
                  "idle": true
                }
            application/json-assembly-running:
              type: AssemblyState
              example: |
                {
                  "running": {
                    "datasetKey": 1140,
                    "attempt": 1,
                    "state": "copying",
                    "started": "2019-10-09T15:33:05.347",
                    "taxonCount": 1110,
                    "type": "SectorSync",
                    "sectorKey": 2729,
                    "ignoredUsageCount": 6,
                    "usagesCount": 0
                  },
                  "failed": 0,
                  "completed": 1,
                  "idle": false
                }
  /{catKey}/sync:
    get:
      description: |
        Get the assembly sync status for catalogue {catKey}
      responses:
        200:
          body:
            application/json:
              type: ResultPage
              example: |
                {
                  "offset": 0,
                  "limit": 25,
                  "total": 2,
                  "result": [
                    {
                      "attempt": 1,
                      "state": "finished",
                      "started": "2019-10-09T16:15:28.471",
                      "finished": "2019-10-09T16:16:09.994",
                      "nameCount": 5979,
                      "taxonCount": 1483,
                      "synonymCount": 4496,
                      "referenceCount": 3905,
                      "distributionCount": 5421,
                      "vernacularCount": 138,
                      "type": "SectorSync",
                      "sectorKey": 2728,
                      "usagesCount": 0
                    },
                    {
                      "attempt": 1,
                      "state": "finished",
                      "started": "2019-10-09T15:33:05.347",
                      "finished": "2019-10-09T15:42:21.107",
                      "nameCount": 57046,
                      "taxonCount": 12959,
                      "synonymCount": 44087,
                      "referenceCount": 36370,
                      "distributionCount": 50063,
                      "vernacularCount": 803,
                      "type": "SectorSync",
                      "sectorKey": 2729,
                      "usagesCount": 0
                    }
                  ],
                  "last": true,
                  "empty": false
                }
    post:
      description: |
        Sync a sector to catalogue {catKey}
      body:
        example: |
          {
            "sectorKey": 2728,
            "datasetKey": 3
          }
      responses:
        201:
        400:
          body:
            application/json-dataset-not-imported-yet:
              description: Bad request when the dataset has not been imported yet.
              example: |
                {
                  "code": 400,
                  "message": "Dataset empty. Cannot sync Sector{2728, datasetKey=3, mode=ATTACH, code=null, subjectDatasetKey=1140, subject=CLASS Lycopodiopsida}"
                }
            application/json-dataset-still-importing:
              description: Bad request when the dataset is currently importing.
              example: |
                {
                  "code": 400,
                  "message": "Dataset 1140 currently being imported. Cannot sync Sector{2728, datasetKey=3, mode=ATTACH, code=null, subjectDatasetKey=1140, subject=CLASS Lycopodiopsida}"
                }
            application/json-sector-does-not-exist:
              description: Sector {sectorKey} does not exist yet.
              example: |
                {
                  "code": 400,
                  "message": "Sector 3453453 does not exist"
                }
            application/json-only-draft-catalogue:
              description: The API only allows assembly on the draft catalogue ({catKey}=3) currently.
              example: |
                {
                  "code": 400,
                  "message": "Only the draft CoL can be assembled at this stage"
                }
        404:
  /{catKey}/sync/{sectorKey}:
    delete:
      description: |
        Delete sector {sectorKey} from catalogue {catKey}.
      responses:
        204:
  /{catKey}/sync/{sectorKey}/{attempt}:
      get:
        description: |
          Get info on sector {sectorKey} sync {attempt} number from catalogue {catKey}.
        responses:
          200:
            body:
              application/json:
                description: Get status and statistics on a sync attempt.
                example: |
                  {
                    "attempt": 1,
                    "state": "finished",
                    "started": "2019-10-09T16:58:30.936",
                    "finished": "2019-10-09T16:59:08.412",
                    "nameCount": 5979,
                    "taxonCount": 1483,
                    "synonymCount": 4496,
                    "referenceCount": 3905,
                    "distributionCount": 5421,
                    "vernacularCount": 138,
                    "type": "SectorSync",
                    "sectorKey": 2728,
                    "usagesCount": 0
                  }
          404:
            body:
              application/json:
                description: Sync attempt not found.
                example: |
                  {
                    "code": 404,
                    "message": "HTTP 404 Not Found"
                  }
  /{catKey}/release:
    post:
      description: |
        Starts a new catalogue release job that copies the given catalogue into a new dataset. 
        The released catalogue will finally be exported into an archive in the download directory.
        Only one job can run at a time.
      responses:
        201:
          body:
            text/plain:
              type: integer
              description: The key of newly created release dataset
              example: 3031
        400:
          body:
            application/json:
              description: The API only allows export of the draft catalogue ({catKey}=3) currently.
              example: |
                {
                  "code": 400,
                  "message": "Only the draft CoL can be assembled at this stage"
                }
    get:
      description: |
        Returns the status of the currently running release job 
      responses:
        200:
          body:
            text/plain:
              type: string
  /{catKey}/rematch:
    post:
      description: |
        Rematches all of the broken sectors and decisions in the {catKey} catalogue assembly.
      body:
        application/json:
          example: |
            {
              "all":true
            }
      responses:
        400:
          body:
            application/json:
              description: The API only allows rematching on the draft catalogue ({catKey}=3) currently.
              example: |
                {
                  "code": 400,
                  "message": "Only the draft CoL can be assembled at this stage"
                }
        404:
          body:
            application/json:
              description: If a dataset is not imported yet, the API returns a 404 error
              example: |
                {
                  "code": 404,
                  "message": "Dataset 1115 does not exist"
                }
