type: object
description: Captures input and options for the name suggestion service (a.k.a. auto-complete service)
properties:
    q:
        type: string
        description: The string to search for (i.e. auto-complete)